### ISSUE TITLE
您好！请问数据集能否提供？或数据集是什么样的格式能否告知，感谢！

### ISSUE THREAD

**Issue by chastelover** [17385/TreeBERT#1]
如题~谢谢！

**Comment by 17385** [comment]
The dataset contains ASTs. ASTs are split by '\n', Paths are split by '\t', and Nodes are separated by '|'.
Thank you for your interest in TreeBERT. 
Full code soon.

**Comment by 17385** [comment]
The dataset contains ASTs. ASTs are split by '\n', Paths are split by '\t', and Nodes are split by '|'.
Thank you for your interest in TreeBERT.
